(defun dzien(n)
    (case (mod n 7)
        (0 "Niedziela")
        (1 "Poniedzialek")
        (2 "Wtorek")
        (3 "Sroda")
        (4 "Czwartek")
        (5 "Piatek")
        (6 "Sobota")
    )
)

(print(dzien 0))
(print(dzien 6))
(print(dzien 7))
(print(dzien 10))